//STOCK-3183
db.getCollection('config_tbl').remove({'featureId':'qtyStatusAtPoReviewScreen'});
db.getCollection('config_tbl').insert([{"locationOrGroupId": "posMClient-grp-all","applicationId": "SAR","moduleId": "stockModule","featureGroup": "purchaseOrder","featureId": "qtyStatusAtPoReviewScreen","featureName": "Quantity Statuses at Purchase Order Review screen","featureDescription": null,"featureType": "dropdown","featureListId": null,"featureValue": "","displaySeqNumber": null,"defaultValue": ["confirmed","unconfirmed","rejected","shipped","receiveInProgress"],"isPublic": "1","parentFeatureId": null,"fileName": "posMClient/sar.ovccfg","visibilityExpression": null,"isDeleted": false,"lastModified": new Date(),"created": new Date(),"__v": 0}]);
//STOCK-2706
db.getCollection("permission_tbl").remove( { "permGroup":"replenishmentFilters","permId": "runReplenishmentFilters" } );

//STOCK-3467
db.getCollection('config_tbl').remove({'featureId':'autoForceCancelDraft'});
db.getCollection('config_tbl').insert({"locationOrGroupId":"posMClient-grp-all","applicationId":"SAR","moduleId":"stockModule","featureGroup":"purchaseOrder","featureId":"autoForceCancelDraft","featureName":"Automatically Cancel Draft Orders without an update after this many days","featureDescription":null,"featureType":"numeric","featureListId":null,"featureValue":"","displaySeqNumber":null,"defaultValue":"60","isPublic":"1","parentFeatureId":null,"fileName":"posMClient/sar.ovccfg","visibilityExpression":null,"isDeleted":false,"lastModified":new Date(),"created":new Date(),"__v":0.0});

//STOCK-2879
db.getCollection('config_tbl').remove({'featureId':'exportBalanceTypes'});
db.getCollection('config_tbl').insert({"locationOrGroupId":"posMClient-grp-all","applicationId":"SAR","moduleId":"stockModule","featureGroup":"stockUpdates","featureId":"exportBalanceTypes","featureName":"Upon every Inventory Balance Update, values for the following Balances should be pushed to the POS:","featureDescription":null,"featureType":"dropDownPreSelect","featureListId":null,"featureValue":"","displaySeqNumber":null,"defaultValue":["oh"],"isPublic":"1","parentFeatureId":null,"fileName":"posMClient/sar.ovccfg","visibilityExpression":null,"isDeleted":false,"lastModified":new Date(),"created":new Date(),"__v":0.0});

//STOCK-3880
db.getCollection("permission_tbl").remove({"permId":{$in:['viewZcounts','modifyZcounts','modifyZcounts','validateZones','approveZcounts']}});
db.getCollection("permission_tbl").insert([{"applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"modifyZcounts","parentId":"viewZcounts","permName":"Edit Counts","permDescription":"Edit Counts","URLState":["ovc.Counts-add","ovc.Counts-edit"],"isDeleted":false,"__v":0,"created":new Date(),"lastModified":new Date()},{"applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"validateZones","parentId":"viewZcounts","permName":"Validate Count Zones","permDescription":"Validate Count Zones","isDeleted":false,"__v":0,"created":new Date(),"lastModified":new Date()},{"applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"approveZcounts","parentId":"viewZcounts","permName":"Approve Counts","permDescription":"Approve Counts","isDeleted":false,"__v":0,"created":new Date(),"lastModified":new Date()},{"applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"viewZcounts","parentId":"","permName":"View Counts","permDescription":"View Counts","URLState":["ovc.Counts-list"],"isDeleted":false,"__v":0,"created":new Date(),"lastModified":new Date()}]);
 
db.getCollection("role_permission_tbl").remove({"permId":{$in:['viewZcounts','modifyZcounts','modifyZcounts','validateZones','approveZcounts']}});
db.getCollection("role_permission_tbl").insert([{"roleId":"5","applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"approveZcounts","isDeleted":false,"access":false,"permValue":null,"__v":0,"created":new Date(),"lastModified":new Date()},{"roleId":"5","applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"validateZones","isDeleted":false,"access":false,"permValue":null,"__v":0,"created":new Date(),"lastModified":new Date()},{"roleId":"5","applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"modifyZcounts","URLState":["ovc.Counts-add","ovc.Counts-edit"],"isDeleted":false,"access":false,"permValue":null,"__v":0,"created":new Date(),"lastModified":new Date()},{"roleId":"5","applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"viewZcounts","URLState":["ovc.Counts-list"],"isDeleted":false,"access":true,"permValue":null,"__v":0,"created":new Date(),"lastModified":new Date()}]);
 
//STOCK-3952
db.getCollection('config_tbl').remove({'featureId':'enableMarkForLocation'});
db.getCollection('config_tbl').insert({"locationOrGroupId":"posMClient-grp-all","applicationId":"SAR","moduleId":"stockModule","featureGroup":"globals","featureId":"enableMarkForLocation","featureName":"Enable Mark for Location","featureDescription":null,"featureType":"boolean","featureListId":null,"featureValue":"","displaySeqNumber":null,"defaultValue":"0","isPublic":"1","parentFeatureId":null,"fileName":"posMClient/sar.ovccfg","visibilityExpression":null,"isDeleted":false,"lastModified":new Date(),"created":new Date(),"__v":0});
 