
//STOCK-634
db.getCollection('config_tbl').remove({'featureId':'autoForceClose'});
db.getCollection('config_tbl').remove({'featureId':'autoForceCloseOrder'});
db.getCollection('config_tbl').insert({"locationOrGroupId":"posMClient-grp-all","applicationId":"SAR","moduleId":"stockModule","featureGroup":"purchaseOrder","featureId":"autoForceCloseOrder","featureName":"Number of days in which Manual Purchase Order is automatically Force Closed","featureDescription":null,"featureType":"numeric","featureListId":null,"featureValue":"","displaySeqNumber":null,"defaultValue":"60","isPublic":"1","parentFeatureId":null,"fileName":"posMClient/sar.ovccfg","visibilityExpression":null,"isDeleted":false,"lastModified":new Date(),"created":new Date(),"__v":0});

// STOCK-3708 
db.getCollection("permission_tbl").remove({"permId":{$in:['viewUnconfirmedOut','viewUnconfirmedIn','viewRejectedIn','viewRejectedOut']}});
db.getCollection("permission_tbl").insert([{"applicationId": "SAR","moduleId": "inventory","permGroup": "stockLookup","permId": "viewUnconfirmedIn","permName": "View Unconfirmed In","permDescription": "View Unconfirmed In","isDeleted": false,"lastModified": new Date(),"created": new Date(),"__v": 0.0}, {"applicationId": "SAR","moduleId": "inventory","permGroup": "stockLookup","permId": "viewUnconfirmedOut","permName": "View Unconfirmed Out","permDescription": "View Unconfirmed Out","isDeleted": false,"lastModified": new Date(),"created": new Date(),"__v": 0.0}, {"applicationId": "SAR","moduleId": "inventory","permGroup": "stockLookup","permId": "viewRejectedIn","permName": "View Rejected In","permDescription": "View Rejected In","isDeleted": false,"lastModified": new Date(),"created": new Date(),"__v": 0.0}, {"applicationId": "SAR","moduleId": "inventory","permGroup": "stockLookup","permId": "viewRejectedOut","permName": "View Rejected Out","permDescription": "View Rejected Out","isDeleted": false,"lastModified": new Date(),"created": new Date(),"__v": 0.0}]);

db.getCollection("role_permission_tbl").remove({"permId":{$in:['viewUnconfirmedOut','viewUnconfirmedIn','viewRejectedIn','viewRejectedOut']}});
db.getCollection("role_permission_tbl").insert([{"roleId": "5","applicationId": "SAR","moduleId": "inventory","permGroup": "stockLookup","permId": "viewUnconfirmedIn","isDeleted": false,"lastModified": new Date(),"created": new Date(),"access": true,"permValue": null,"__v": 0}, {"roleId": "5","applicationId": "SAR","moduleId": "inventory","permGroup": "stockLookup","permId": "viewUnconfirmedOut","isDeleted": false,"lastModified": new Date(),"created": new Date(),"access": true,"permValue": null,"__v": 0}, {"roleId": "5","applicationId": "SAR","moduleId": "inventory","permGroup": "stockLookup","permId": "viewRejectedIn","isDeleted": false,"lastModified": new Date(),"created": new Date(),"access": true,"permValue": null,"__v": 0}, {"roleId": "5","applicationId": "SAR","moduleId": "inventory","permGroup": "stockLookup","permId": "viewRejectedOut","isDeleted": false,"lastModified": new Date(),"created": new Date(),"access": true,"permValue": null,"__v": 0}]);

//STOCK-3848 // STOCK-3881
db.getCollection("permission_tbl").remove({"permId":{$in:['viewBalanceReport','viewStockStatusReport','viewStockBalanceReport']}});
db.getCollection("permission_tbl").insert([{"applicationId": "SAR","moduleId": "reports","permGroup": "stockStatusReport","permId": "viewStockStatusReport","permName": "View Stock Status Report","permDescription": "View Stock Status Report","isDeleted": false,"lastModified": new Date(),"created": new Date(),"__v": 0.0}, {"applicationId": "SAR","moduleId": "reports","permGroup": "balanceReport","permId": "viewBalanceReport","permName": "View Balance Report","permDescription": "View Balance Report","isDeleted": false,"lastModified": new Date(),"created": new Date(),"__v": 0.0}]);

db.getCollection("role_permission_tbl").remove({"permId":{$in:['viewBalanceReport','viewStockStatusReport']}});
db.getCollection("role_permission_tbl").insert([{"roleId": "5","applicationId": "SAR","moduleId": "reports","permGroup": "balanceReport","permId": "viewBalanceReport","isDeleted": false,"lastModified": new Date(),"created": new Date(),"access": true,"permValue": null,"__v": 0}, {"roleId": "5","applicationId": "SAR","moduleId": "reports","permGroup": "stockStatusReport","permId": "viewStockStatusReport","isDeleted": false,"lastModified": new Date(),"created": new Date(),"access": true,"permValue": null,"__v": 0}]);

//STOCK-3869
db.getCollection('config_tbl').remove({'featureId':'checkNeedbydate'});
db.getCollection('config_tbl').insert({"locationOrGroupId":"posMClient-grp-all","applicationId":"SAR","moduleId":"stockModule","featureGroup":"purchaseOrder","featureId":"checkNeedbydate","featureName":"Automatically mark orders as 'Completed' based on 'Need by date'","featureDescription":null,"featureType":"boolean","featureListId":null,"featureValue":"","displaySeqNumber":null,"defaultValue":"0","isPublic":"1","parentFeatureId":null,"fileName":"posMClient/sar.ovccfg","visibilityExpression":null,"isDeleted":false,"lastModified":new Date(),"created":new Date(),"__v":0});
//STOCK-4035
db.getCollection('config_tbl').remove({'featureId':'replenishmentRounding'});
db.getCollection('config_tbl').insert({"locationOrGroupId":"posMClient-grp-all","applicationId":"SAR","moduleId":"stockModule","featureGroup":"purchaseOrder","featureId":"replenishmentRounding","featureName":"Replenishment Rounding","featureDescription":null,"featureType":"singleselectdropdown","featureListId":null,"featureValue":"","displaySeqNumber":null,"defaultValue":"0","isPublic":"1","parentFeatureId":null,"fileName":"posMClient/sar.ovccfg","visibilityExpression":null,"isDeleted":false,"lastModified":new Date(),"created":new Date(),"__v":0});
db.getCollection('config_tbl').remove({'featureId':'replenishmentRoundingUOM'});
db.getCollection('config_tbl').insert({"locationOrGroupId":"posMClient-grp-all","applicationId":"SAR","moduleId":"stockModule","featureGroup":"purchaseOrder","featureId":"replenishmentRoundingUOM","featureName":"Replenishment Rounding UOM","featureDescription":null,"featureType":"text","featureListId":null,"featureValue":"","displaySeqNumber":null,"defaultValue":"Each","isPublic":"1","parentFeatureId":null,"fileName":"posMClient/sar.ovccfg","visibilityExpression":null,"isDeleted":false,"lastModified":new Date(),"created":new Date(),"__v":0});
db.getCollection('config_tbl').remove({'featureId':'replenishmentRoundingBaseQty'});
db.getCollection('config_tbl').insert({"locationOrGroupId":"posMClient-grp-all","applicationId":"SAR","moduleId":"stockModule","featureGroup":"purchaseOrder","featureId":"replenishmentRoundingBaseQty","featureName":"Replenishment Rounding BaseQty","featureDescription":null,"featureType":"numeric","featureListId":null,"featureValue":"","displaySeqNumber":null,"defaultValue":"1","isPublic":"1","parentFeatureId":null,"fileName":"posMClient/sar.ovccfg","visibilityExpression":null,"isDeleted":false,"lastModified":new Date(),"created":new Date(),"__v":0});
// db.getCollection('config_tbl').remove({'featureId':'displayStockingLocationsWidget'});
// db.getCollection('config_tbl').insert({"locationOrGroupId":"posMClient-grp-all","applicationId":"SAR","moduleId":"stockModule","featureGroup":"stockingLocationsWidget","featureId":"displayStockingLocationsWidget","featureName":"Widget to Stocking locations display","featureDescription":null,"featureType":"boolean","featureListId":null,"featureValue":"","displaySeqNumber":null,"defaultValue":"1","isPublic":"1","parentFeatureId":null,"fileName":"posMClient/sar.ovccfg","visibilityExpression":null,"isDeleted":false,"lastModified":new Date(),"created":new Date(),"__v":0});

//STOCK-3880
db.getCollection("permission_tbl").remove({"permId":{$in:['viewZcounts','modifyZcounts','modifyZcounts','validateZones','approveZcounts']}});
db.getCollection("permission_tbl").insert([{"applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"modifyZcounts","parentId":"viewZcounts","permName":"Edit Counts","permDescription":"Edit Counts","URLState":["ovc.Counts-add","ovc.Counts-edit"],"isDeleted":false,"__v":0,"created":new Date(),"lastModified":new Date()},{"applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"validateZones","parentId":"viewZcounts","permName":"Validate Count Zones","permDescription":"Validate Count Zones","isDeleted":false,"__v":0,"created":new Date(),"lastModified":new Date()},{"applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"approveZcounts","parentId":"viewZcounts","permName":"Approve Counts","permDescription":"Approve Counts","isDeleted":false,"__v":0,"created":new Date(),"lastModified":new Date()},{"applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"viewZcounts","parentId":"","permName":"View Counts","permDescription":"View Counts","URLState":["ovc.Counts-list"],"isDeleted":false,"__v":0,"created":new Date(),"lastModified":new Date()}]);
 
db.getCollection("role_permission_tbl").remove({"permId":{$in:['viewZcounts','modifyZcounts','modifyZcounts','validateZones','approveZcounts']}});
db.getCollection("role_permission_tbl").insert([{"roleId":"5","applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"approveZcounts","isDeleted":false,"access":false,"permValue":null,"__v":0,"created":new Date(),"lastModified":new Date()},{"roleId":"5","applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"validateZones","isDeleted":false,"access":false,"permValue":null,"__v":0,"created":new Date(),"lastModified":new Date()},{"roleId":"5","applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"modifyZcounts","URLState":["ovc.Counts-add","ovc.Counts-edit"],"isDeleted":false,"access":false,"permValue":null,"__v":0,"created":new Date(),"lastModified":new Date()},{"roleId":"5","applicationId":"SAR","moduleId":"counts","permGroup":"zCounts","permId":"viewZcounts","URLState":["ovc.Counts-list"],"isDeleted":false,"access":true,"permValue":null,"__v":0,"created":new Date(),"lastModified":new Date()}]);
 
//STOCK-3952
db.getCollection('config_tbl').remove({'featureId':'enableMarkForLocation'});
db.getCollection('config_tbl').insert({"locationOrGroupId":"posMClient-grp-all","applicationId":"SAR","moduleId":"stockModule","featureGroup":"globals","featureId":"enableMarkForLocation","featureName":"Enable Mark for Location","featureDescription":null,"featureType":"boolean","featureListId":null,"featureValue":"","displaySeqNumber":null,"defaultValue":"0","isPublic":"1","parentFeatureId":null,"fileName":"posMClient/sar.ovccfg","visibilityExpression":null,"isDeleted":false,"lastModified":new Date(),"created":new Date(),"__v":0});

